<a href="https://colab.research.google.com/github/sonjoy1s/Rnn_DeepLearning/blob/main/RNN_module3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import pandas as pd

In [22]:
df = pd.read_csv("/content/gk_qna_dataset.csv")
df.head()

,question,answer
0,"What is the capital of ""France""?",Paris
1,"What is the capital of ""Germany""?",Berlin
2,"What is the capital of ""Italy""?",Rome
3,"What is the capital of ""Spain""?",Madrid
4,"What is the capital of ""Japan""?",Tokyo


In [23]:
df['question'][1]

'What is the capital of "Germany"?'

**Tokenize**

In [24]:
import re
def tokenize(text):
  #Lowercase
  text = text.lower()


  #romoved quotes
  text = re.sub(r"[\"']","",text)
  text = re.sub(r"[‘’]","",text)

  #removed all punctuation
  text = re.sub(r"[^\w\s]","",text)
  punctuations = re.sub(r"[^a-z0-9\s]"," ",text)

  #removed extra space
  text = text.replace("\n", " ")


  #tokenize split into words
  tokens = text.split()

  return tokens

In [25]:
print(tokenize(df['question'][9]))

['what', 'is', 'the', 'capital', 'of', 'china']


vocab formating

In [26]:
vocab ={'<UNK>':0}

In [27]:
vocab

{'<UNK>': 0}

In [39]:
def build_vocab(row):
 # print(row['question'],row['answer'])
  tokenize_question = tokenize(row['question'])
  tokenize_answer = tokenize(row['answer'])


  #print(tokenize_question)
  #print(tokenize_answer)

  # merge tokenize
  merge_tokens = tokenize_question + tokenize_answer

  #print(merge_tokens)

  for token in merge_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)



In [40]:
df.apply(build_vocab,axis=1)

,0
0,None
1,None
2,None
3,None
4,None
...,...
166,None
167,None
168,None
169,None


In [41]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq

**text** **to** **indices**

In [44]:
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    #print(token)
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [45]:
text_to_indices("what is Phitron",vocab)

[1, 2, 0]

# Dataset and dataloader

In [47]:
import torch
from torch.utils.data import Dataset,DataLoader

In [48]:
df.shape[0]

171

In [54]:
index = 0
text_to_indices(df.iloc[index]['question'],vocab)

[1, 2, 3, 4, 5, 6]

In [61]:
class QADataset(Dataset):
  def __init__(self,df,vocab):

    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,idx):
    numerical_question = text_to_indices(self.df.iloc[index]['question'],vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'],vocab)


    return torch.tensor(numerical_question),torch.tensor(numerical_answer)


In [62]:
dataset = QADataset(df,vocab)

In [63]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

# DataLoader

In [64]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [65]:
for question,answer in dataloader:
  print(question)
  print(answer)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1,