<a href="https://colab.research.google.com/github/sonjoy1s/Rnn_DeepLearning/blob/main/RNN_module3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import pandas as pd

In [118]:
df = pd.read_csv("/content/gk_qna_dataset.csv")
df.head()

,question,answer
0,"What is the capital of ""France""?",Paris
1,"What is the capital of ""Germany""?",Berlin
2,"What is the capital of ""Italy""?",Rome
3,"What is the capital of ""Spain""?",Madrid
4,"What is the capital of ""Japan""?",Tokyo


In [119]:
df['question'][1]

'What is the capital of "Germany"?'

**Tokenize**

In [120]:
import re
def tokenize(text):
  #Lowercase
  text = text.lower()


  #romoved quotes
  text = re.sub(r"[\"']","",text)
  text = re.sub(r"[‘’]","",text)

  #removed all punctuation
  text = re.sub(r"[^\w\s]","",text)
  punctuations = re.sub(r"[^a-z0-9\s]"," ",text)

  #removed extra space
  text = text.replace("\n", " ")


  #tokenize split into words
  tokens = text.split()

  return tokens

In [121]:
print(tokenize(df['question'][9]))

['what', 'is', 'the', 'capital', 'of', 'china']


vocab formating

In [122]:
vocab ={'<UNK>':0}

In [123]:
vocab

{'<UNK>': 0}

In [124]:
def build_vocab(row):
 # print(row['question'],row['answer'])
  tokenize_question = tokenize(row['question'])
  tokenize_answer = tokenize(row['answer'])


  #print(tokenize_question)
  #print(tokenize_answer)

  # merge tokenize
  merge_tokens = tokenize_question + tokenize_answer

  #print(merge_tokens)

  for token in merge_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)



In [125]:
df.apply(build_vocab,axis=1)

,0
0,None
1,None
2,None
3,None
4,None
...,...
166,None
167,None
168,None
169,None


In [126]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq

**text** **to** **indices**

In [127]:
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    #print(token)
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [128]:
text_to_indices("what is Phitron",vocab)

[1, 2, 0]

# Dataset and dataloader

In [129]:
import torch
from torch.utils.data import Dataset,DataLoader

In [130]:
df.shape[0]

171

In [131]:
index = 0
text_to_indices(df.iloc[index]['question'],vocab)

[1, 2, 3, 4, 5, 6]

In [132]:
class QADataset(Dataset):
  def __init__(self,df,vocab):

    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,idx):
    numerical_question = text_to_indices(self.df.iloc[index]['question'],vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'],vocab)


    return torch.tensor(numerical_question),torch.tensor(numerical_answer)


In [133]:
dataset = QADataset(df,vocab)

In [134]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

# DataLoader

In [135]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [136]:
for question,answer in dataloader:
  print(question)
  print(answer)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[7]])
tensor([[1,

# RNN Architecture

In [137]:
import torch.nn as nn

class simpleRNN(nn.Module):
  def __init__(self, vocab_size, embedding_dim = 50 , hidden_size=64):
    super(simpleRNN, self).__init__()

    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.rnn = nn.RNN(embedding_dim, hidden_size, batch_first=True)
    self.fc = nn.Linear(hidden_size, vocab_size)

# forward
  def forward(self, x):
    x = self.embedding(x) # x: (batch_size, seq_len, embedding_dim)
    _, final = self.rnn(x) # final: (num_layers * num_directions, batch_size, hidden_size)

    # Squeeze the first dimension of 'final' to get (batch_size, hidden_size)
    final_hidden_state = final.squeeze(0)

    # Pass the final hidden state to the linear layer
    x = self.fc(final_hidden_state) # x: (batch_size, vocab_size)
    return x

In [138]:
model = simpleRNN(len(vocab))

In [139]:
model

simpleRNN(
  (embedding): Embedding(243, 50)
  (rnn): RNN(50, 64, batch_first=True)
  (fc): Linear(in_features=64, out_features=243, bias=True)
)

In [140]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epochs = 50

In [141]:
for epoch in range(epochs):
  total_loss = 0
  for question,answer in dataloader:
    optimizer.zero_grad()
    output = model(question)

    target = answer[0][0].unsqueeze(0)

    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    total_loss += loss.item()

  if (epoch+1)%10 ==0:
    print(f"Epoch{epoch+1:3d}/{epoch} | Loss : {total_loss : .4f}")

Epoch 10/9 | Loss :  0.0683
Epoch 20/19 | Loss :  0.0164
Epoch 30/29 | Loss :  0.0058
Epoch 40/39 | Loss :  0.0023
Epoch 50/49 | Loss :  0.0008


# Prediction

In [142]:
idx_to_word = {index: word for word, index in vocab.items()}

In [143]:
idx_to_word

{0: '<UNK>',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france',
 7: 'paris',
 8: 'germany',
 9: 'berlin',
 10: 'italy',
 11: 'rome',
 12: 'spain',
 13: 'madrid',
 14: 'japan',
 15: 'tokyo',
 16: 'canada',
 17: 'ottawa',
 18: 'brazil',
 19: 'brasilia',
 20: 'australia',
 21: 'canberra',
 22: 'india',
 23: 'new',
 24: 'delhi',
 25: 'china',
 26: 'beijing',
 27: 'russia',
 28: 'moscow',
 29: 'united',
 30: 'states',
 31: 'washington',
 32: 'dc',
 33: 'mexico',
 34: 'city',
 35: 'egypt',
 36: 'cairo',
 37: 'turkey',
 38: 'ankara',
 39: 'argentina',
 40: 'buenos',
 41: 'aires',
 42: 'south',
 43: 'korea',
 44: 'seoul',
 45: 'indonesia',
 46: 'jakarta',
 47: 'pakistan',
 48: 'islamabad',
 49: 'bangladesh',
 50: 'dhaka',
 51: 'nepal',
 52: 'kathmandu',
 53: 'sri',
 54: 'lanka',
 55: 'colombo',
 56: 'thailand',
 57: 'bangkok',
 58: 'malaysia',
 59: 'kuala',
 60: 'lumpur',
 61: 'vietnam',
 62: 'hanoi',
 63: 'uae',
 64: 'abu',
 65: 'dhabi',
 66: 'iran',
 67: 'tehran',
 68: '

In [115]:
def prediction(model, question, idx_to_word):
  model.eval()
  with torch.no_grad():
    indices = text_to_indices(question, vocab)
    if not indices:
      return "<UNK>"

    x = torch.tensor(indices).unsqueeze(0)

    pred = torch.argmax(model(x), dim=1).item()

    return idx_to_word[pred]

In [145]:
#TEST
tests = [
    "what is the capital of France?",
    "How is H2O Commonly called?",
]
for q in tests:
  print(f"{q:45} -> {prediction(model, q, idx_to_word)}")

what is the capital of France?                -> paris
How is H2O Commonly called?                   -> da
